---
description: "MambaDB is a state-of-the-art inventory system."
timezone: America/Puerto_Rico
markdown: kramdown
highligther: rouge
title: MambaDB
logo: /assets/images/logo.png
url: https://mambadb.titanpointe.org
email: support@titanpointe.org
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
sass:
    sass_dir: _scss
    style: compressed
theme: jekyll-theme-minimal